name: 'telegram_data_pipeline' # Project name must use underscores, not hyphens
version: '1.0.0'
config-version: 2

profile: 'telegram_data_pipeline' # Must match the name in profiles.yml

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"
  - "dbt_modules"

models:
  telegram_data_pipeline: # Must match the project name
    +materialized: view # Default for all models in this project
    +schema: analytics # Default schema for final analytical models

    staging:
      +materialized: view # Staging models as views
      +schema: staging # Staging models in a separate schema

    marts:
      +materialized: table # Marts as tables for performance
      +schema: analytics # Final analytical models
