name: 'telegram_data_pipeline'
version: '1.0.0'
config-version: 2

profile: 'telegram_data_pipeline'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"
  - "dbt_modules"

models:
  telegram_data_pipeline:
    +materialized: view
    # +schema: analytics

    staging:
      +materialized: view
      # +schema: staging

    marts:
      +materialized: table
      # +schema: analytics
