telegram-data-pipeline: # This is your dbt project name (from dbt_project.yml) - UPDATED
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('POSTGRES_HOST') }}"
      port: "{{ env_var('POSTGRES_PORT') | int }}"
      user: "{{ env_var('POSTGRES_USER') }}"
      password: "{{ env_var('POSTGRES_PASSWORD') }}"
      dbname: "{{ env_var('POSTGRES_DB') }}"
      schema: public # Default schema for dbt models, can be overridden per model
      threads: 4 # Number of concurrent connections dbt can use
      # Optional: set a search_path if you have multiple schemas and want to prioritize
      # search_path: [raw, public]
